version: "3.8"

services:
  kmq:
    image: kmq-dev-bot
    build:
      context: ../
      dockerfile: docker/kmq/Dockerfile
      args: 
        NODE_ENV: ${NODE_ENV}
    env_file: .env
    environment:
      SONG_DOWNLOAD_DIR: /songs
    volumes:
      - songs:/songs
      - dump:/dump
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 5858:5858

  db:
    image: mariadb:10.3
    restart: on-failure
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --max-allowed-packet=32M
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 12

volumes:
  songs:
  dump:
  mysql:
