version: "3.8"

services:
  kmq:
    image: kmq-dev-bot
    build:
      context: ../
      dockerfile: docker/kmq/Dockerfile
      args: 
        START_TYPE: ${START_TYPE}
    env_file: .env
    environment:
      SONG_DOWNLOAD_DIR: /songs
    volumes:
      - songs:/songs
      - dump:/dump
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: on-failure
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  songs:
  dump:
  mysql:
