version: "3.8"

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - songs:/songs
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        network_mode: service:db

    db:
        image: mariadb:10.6.17
        restart: on-failure
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 3307:3306
        command: --max-allowed-packet=32M
        healthcheck:
            test: mysql --password=$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'
            timeout: 20s
            interval: 5s
            retries: 10
volumes:
    mysql:
    songs:
