declare namespace NodeJS {
    export interface ProcessEnv {
        BOT_TOKEN: string | undefined;
        BOT_CLIENT_ID: string | undefined;
        DB_USER: string | undefined;
        DB_PASS: string | undefined;
        DB_HOST: string | undefined;
        DB_PORT: string | undefined;
        SONG_DOWNLOAD_DIR: string | undefined;
        TOP_GG_TOKEN?: string | undefined;
        TOP_GG_WEBHOOK_AUTH?: string | undefined;
        DISCORD_BOTS_GG_TOKEN?: string | undefined;
        DISCORD_BOT_LIST_TOKEN?: string | undefined;
        KOREAN_BOTS_TOKEN?: string | undefined;
        DEBUG_SERVER_ID?: string | undefined;
        DEBUG_TEXT_CHANNEL_ID?: string | undefined;
        BOT_PREFIX: string | undefined;
        NODE_ENV: string | undefined;
        WEB_SERVER_PORT: string | undefined;
        ALERT_WEBHOOK_URL?: string | undefined;
        DEBUG_LOGGING?: string | undefined;
        POWER_HOUR_NOTIFICATION_CHANNEL_ID?: string | undefined;
        POWER_HOUR_NOTIFICATION_ROLE_ID?: string | undefined;
        SPOTIFY_CLIENT_ID?: string | undefined;
        SPOTIFY_CLIENT_SECRET?: string | undefined;
        DAISUKI_SEED_CRON_JOB?: string | undefined;
        GUILDS_PER_SHARD?: string | undefined;
        APP_NAME: string | undefined;
        AZURE_STORAGE_SAS_TOKEN?: string | undefined;
        DAISUKI_DB_PASSWORD?: string | undefined;
        IS_STANDBY?: string | undefined;
        REDDIT_CLIENT_ID?: string | undefined;
        REDDIT_CLIENT_SECRET?: string | undefined;
        REDDIT_CLIENT_REFRESH_TOKEN?: string | undefined;
        GEMINI_API_KEY?: string | undefined;
        MINIMAL_RUN?: string | undefined;
        YOUTUBE_API_KEY?: string | undefined;
    }
}
