name: docker-build

on:
  push:
    branches: [ master ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker_build.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - 'docker/**'
      - .github/workflows/docker_build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build --file docker/kmq/Dockerfile . --tag kmq-ci
      - name: Anchore Container Scan
        # You may pin to the exact commit or the version.
        # uses: anchore/scan-action@3c947f31798e0e3e9fa2bf18282aeb57a1a4aaa5
        uses: anchore/scan-action@v2.0.4
        with:
          image: kmq-ci
          fail-build: false
      - name: Dry-run
        run: docker run -e NODE_ENV='ci' kmq-ci
