name: E2E

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths: 
      - .github/workflows/e2e.yml
      - src/seed/seed_db.ts
      - src/scripts/download-new-songs.ts
      - src/seed/bootstrap.ts

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_PASS_CI: kmq_ci_password
      DB_USER_CI: root
      DB_PORT: 3306
    steps:
      - name: Checkout KMQ_Discord
        uses: actions/checkout@v2
      - name: Copy .env for CI
        run: |
          echo "DB_USER=$DB_USER_CI" >> docker/.env
          echo "DB_PASS=$DB_PASS_CI" >> docker/.env
          echo "DB_PORT=$DB_PORT" >> docker/.env
          echo "DB_HOST=db" >> docker/.env
      - name: Build and bootstrap dry-run
        run: npm run docker-dryrun
      - name: Post-bootstrap dry-run
        run: npm run docker-dryrun
