name: E2E

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'images/**'
      - 'sql/**'
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_PASS_CI: kmq_ci_password
      DB_USER_CI: kmq_ci
    steps:
      - name: Copy .env for CI
        run: |
          echo "DB_USER=$DB_USER_CI" >> .env
          echo "DB_PASS=$DB_PASS_CI" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
      - name: Setup MySQL server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'kmq_test'
          mysql version: '5.7' 
          mysql user: '$DB_USER_CI'
          mysql password: '$DB_PASS_CI'
      - name: Wait for MySQL server to start
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password="$DB_PASS_CI" --silent; do
            sleep 1
          done
          mysql --port 3306 --host=127.0.0.1 -u $DB_USER_CI --password="$DB_PASS_CI" -e "GRANT ALL ON *.* to $DB_USER_CI@'%' IDENTIFIED BY 'password';"    
      - name: Checkout KMQ_Discord
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: Run tests
        run: npm run test_ci
      - name: Build and E2E dry-run
        run: npm run dry-run
