name: i18n-ai-translate

on:
  pull_request:
    branches:
      - master
    paths:
      - 'i18n/en.json'

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn add i18n-ai-translate

    - name: Setup Git Config
      run: |
        git config --global user.name 'KMQ GH Action Committer'
        git config --global user.email '<>'

    - name: Copy .env for CI
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "API_KEY=$GEMINI_API_KEY" >> .env
      shell: bash

    - name: Fetch original translation
      run: |
        cp i18n/en.json i18n/en-latest.json
        git checkout origin/master -- i18n/en.json

    - name: Translate the diff
      run: |
        npx i18n-ai-translate diff -b i18n/en.json -a i18n/en-latest.json -l "English" --verbose
        mv i18n/en-latest.json i18n/en.json
        git add .
        git commit -m "Update translations" || echo "No changes to commit"
        git push

    - name: Lint translations
      run: npm run lint-i18n-ci

    - name: Check for missing translations
      run: npx ts-node src/ci_checks/missing_i18n.ts $(find src -name '*.ts' -print)
