name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'images/**'
      - 'sql/**'
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout KMQ_Discord
        uses: actions/checkout@v2
      - name: Check for undocumented game option commands
        run: src/ci_checks/check_help.sh
      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Check for newly introduced environment variables
        run: python src/ci_checks/check_env_var.py
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - run: npm install
      - name: npm run lint
        run: npm run lint
      - name: Copy .env for CI
        run: cp .env.ci .env
        shell: bash
      - name: Setup MySQL server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'kmq_test'
          mysql version: '5.7' 
          mysql user: 'kmq_ci'
          mysql password: 'kmq_ci_password'
      - name: Wait for MySQL server to start
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=kmq_ci_password --silent; do
            sleep 1
          done
      - name: Run tests
        run: npm run test
      - name: Build and dry-run
        run: npm run start
        env: 
            START_TYPE: dry-run
