# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout KMQ_Discord
        uses: actions/checkout@v2
      - name: Check for undocumented game option commands
        run: ./src/check_help.sh
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - run: npm install
      - name: tsc
        uses: iCrawl/action-tsc@v1
      - name: npm run lint
        run: npm run lint
      - name: Dry run
        run: ./start.sh dry-run
