name: upgrade

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string
        secrets:
            SSH_DEPLOY_PRIVATE_KEY:
                required: true
            PROD_SSH_ADDRESS:
                required: true
            PROD_SSH_USER:
                required: true
jobs:
    upgrade:
        env:
            KMQ_DIR: /home/kmq/prod
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Install SSH Keys
              run: |
                  echo "Installing SSH keys"
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.PROD_SSH_ADDRESS }} > ~/.ssh/known_hosts
            - name: Redeploy over SSH
              run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_ADDRESS }} "source ~/.zshrc; ./.github/workflows/redeploy_prod.sh $KMQ_DIR ${{ inputs.image-name }}"
