name: upgrade

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string
        secrets:
            SSH_DEPLOY_PRIVATE_KEY:
                required: true
            PROD_SSH_ADDRESS:
                required: true
            PROD_SSH_USER:
                required: true
jobs:
    upgrade:
        env:
            KMQ_DIR: /home/kmq/prod
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Install SSH Keys
              run: |
                  echo "Installing SSH keys"
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.PROD_SSH_ADDRESS }} > ~/.ssh/known_hosts
            - name: Redeploy over SSH
              run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_ADDRESS }} "source ~/.zshrc; ./.github/workflows/redeploy_prod.sh $KMQ_DIR ${{ inputs.image-name }}"
            - name: Wait for KMQ up
              run: timeout 120 bash -c 'until curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:5858/ping | grep -q "^200$"; do sleep 5; done' || { echo "KMQ did not return 200 within 1 minute"; exit 1; }
            - name: Run basic options test
              run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_ADDRESS }} "docker exec kmq-prod sh -c '. ./.env && npx ts-node --swc src/test/end-to-end-tests/test-runner-bot.ts --test-suite=BASIC_OPTIONS --debug --stage-delay=5'"
            - name: Run basic gameplay test
              run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_ADDRESS }} "docker exec kmq-prod sh -c '. ./.env && npx ts-node --swc src/test/end-to-end-tests/test-runner-bot.ts --test-suite=PLAY --debug --stage-delay=5'"
